clear;
load('castleLake2.mat');
msPts = cat(3,pts_out4,xy_out4);
options.csIn = csize4;
options.debug = 1;
options.mode = 'C';
bw = [8,8,20];
[pts_out,xy_out,csize,clusters,cxy] = meanShiftSegment8(msPts,bw,options);
options.crand = 1;
[~,~,~,clusters2,~] = meanShiftSegment8(msPts,bw,options);
[~,~,~,clusters3,~] = meanShiftSegment8(msPts,bw,options);
[~,~,~,clusters4,~] = meanShiftSegment8(msPts,bw,options);
[~,~,~,clusters5,~] = meanShiftSegment8(msPts,bw,options);
[~,~,~,clusters6,~] = meanShiftSegment8(msPts,bw,options);
[~,~,~,clusters7,~] = meanShiftSegment8(msPts,bw,options);
figure;
subplot(3,3,1);
imshow(im4);
subplot(3,3,2);
imshow(lab2rgb(pts_out));
subplot(3,3,3);
imshow(lab2rgb(clusters));
subplot(3,3,4);
imshow(lab2rgb(clusters2));
subplot(3,3,5);
imshow(lab2rgb(clusters3));
subplot(3,3,6);
imshow(lab2rgb(clusters4));
subplot(3,3,7);
imshow(lab2rgb(clusters5));
subplot(3,3,8);
imshow(lab2rgb(clusters6));
subplot(3,3,9);
imshow(lab2rgb(clusters7));